### ISSUE TITLE
MVP Task List

### ISSUE THREAD

**Issue by stefnotch** [wgsl-tooling-wg/wesl-spec#54]
### Introduction
We are building a minimal version of WESL, to let our first users enjoy a modular shading language along with IDE tooling! In this version, we're limiting ourselves to the bare necessities, and are prioritizing the most common use-cases. If *you* need a feature, let us know. Or even better, join in and help us ship this sooner.

We invite everyone to come and help out! There's a lot to do, from setting up a web documentation to extending language servers. 

### Tasklist

Sorted in order of importance

- [ ] 1 working WESL linker
  - [ ] Rust linker 
  - [ ] JS linker (@mighdoll and @stefnotch)
- [ ] Features
  - [x] Imports
    - [x] Spec (@stefnotch)
  - [ ] Conditional compilation
  - [ ] ~~Out of scope: wesl.toml (#57)~~
  - [x] Injecting code: Overrides are enough for now. (https://github.com/wgsl-tooling-wg/wesl-spec/issues/54#issuecomment-2408901953)
  - [ ] Mangling and host code exposing: Linker specific for now (#89)
  - [ ] Stretch goal: Super basic "provide string to linker - aka library"
- [ ] Documentation like [gleam](https://gleam.run/documentation/) - start with GitHub wiki (@stefnotch)
  - [x] Super basic intro ([done](https://github.com/wgsl-tooling-wg/wesl-spec/wiki))
  - [ ] Demo page
  - [x] Language tour/Reference ([done](https://github.com/wgsl-tooling-wg/wesl-spec/wiki))
  - [ ] Stretch goal: Cheatsheet
  - [ ] Installation guide 
    - [x] wesl-rs ([done](https://github.com/wgsl-tooling-wg/wesl-spec/wiki/Getting-Started-(Rust)))
    - [ ] wesl-js ([TBD](https://github.com/wgsl-tooling-wg/wesl-spec/wiki/Getting-Started-(JavaScript)))
- [ ] IDE Tooling: 
  - [ ] Syntax highlighting
    - [x] tree-sitter ([done](https://github.com/wgsl-tooling-wg/tree-sitter-wesl))
    - [ ] VSCode TexMate TBD
  - [ ] Language Server 
    - [ ] Depends on: Spec, linker implementation, test code

**Comment by stefnotch** [comment]
@ncthbrt Does this sound good

**Comment by ncthbrt** [comment]
That seems good. Though how does the language server work without a manifest for modules? Just thinking about bevy's use case

**Comment by ncthbrt** [comment]
While that makes sense, it is a bit unfortunate as this immediately rules out bevy as an initial consumer unless we somehow special case it.

**Comment by stefnotch** [comment]
Right, a language server couldn't resolve `import bevy_pbr::some::absolute::path` without a `wesl.toml`.

Well, time for me to write up a minimal `wesl.toml` proposal for language servers. 

Is there anything else that Bevy needs?

**Comment by ncthbrt** [comment]
Conditional compilation for sure. And the ability to import bindings are a
must.

The ability to integrate with the asset loader system is also important.
The loader uses the asset path to determine what asset loader to use.

**Comment by k2d222** [comment]
> [x] Injecting code: Overrides are enough for now. (@k2d222 Please double-check)

The situations in the WGSL spec where overrides are not allowed but constants are:

- the element count of a fixed-size array (EXCEPT that the outermost array's element count of a var<workgroup> may be an override)
- case selector expressions
- @align, @binding, @blend_src, @group, @id, @location, @size (interestingly, NOT @workgroup_size which can accept overrides).
- the component and offset parameters of `textureGather*` and `textureSample*` functions
- naturally, const-declarations and const-assertions.

So, it seems it's still the case that arrays sizes must be const-expressions. except that one edge case. 

Still, I'm checking that mark anyways. Linker implementations will always be free to override an import (which is the trick I used in my personal project) which allows injecting arbitrary code. It does not have to be part of the WESL standard for now. For libraries, they cannot use this non-standard extension and would therefore have to abstain themselves from hitting one of these edge-cases.

**Comment by stefnotch** [comment]
@k2d222 Thank you very much! And good to know what the workaround is, and what limitations it comes with. I suppose we'll have to address it in a future version. :)

**Comment by mighdoll** [comment]
[this vscode doc](https://code.visualstudio.com/docs/editor/vscode-web%5C#_language-support) left me a little confused about the need for tree-sitter. It seems to suggest that a language server is all you need, but I'm not sure if I'm reading it correctly..

**Comment by mighdoll** [comment]
Since we're inviting more people to review this issue, I'd suggest we add a brief intro above the task list, defining the MVP, its goals and context with our work.

**Comment by mighdoll** [comment]
Since `override` isn't enough, ought have something in as a stretch goal feature in for MVP? It seems possible if we want it e.g. for bevy or other key early projects. 

@k2d222 your demo showed we could generate new `const` elements from a `link()` api. That might be enough.

If we think an MVP language server might complain unless we rewrite elements that are already in the WGSL, we could do that with e.g. your unitialized consts proposal. (And for MVP, I suppose we could just make these global, e.g. not worry about package or module namespacing).

**Comment by ncthbrt** [comment]
This is mostly bikeshedding but I'm somewhat against the syntax of link rather than the idea in principle.

**Comment by mighdoll** [comment]
close once we have issues filed separately
